version: "3.8"

services:
  pgdb:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '8000:8000'
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
