services:
  pgdb:
    image: postgres:14
    container_name: POSTGRES
    restart: always
    environment:
      - POSTGRES_USER=fedonyuk
      - POSTGRES_PASSWORD=74fedonyuk74
      - POSTGRES_DB=postgres01
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test_db:
    image: postgres:14
    container_name: TEST_DB
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    command: -p 5452
    ports:
      - '5452:5452'
#    volumes:
#      - test_postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
#  test_postgres_data:
