openapi: 3.0.0
info:
  title: SQL - Flask Restful API Documentation
  description: API documentation for application SQL
  version: 1.0.0
paths:
  /students/:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/students.yaml'
  /students/{id}:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/students.yaml'
  /groups/students:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/groups.yaml'
  /groups/{num}/students:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/groups.yaml'
  /courses/:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/courses.yaml'
  /courses/{id}:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/courses.yaml'
  /courses/{course}/students/:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/student_course.yaml'
  /students/{id}/courses/:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/student_course.yaml'
  /students/{id_student}/courses/{id_course}:
    $ref: 'C:/Users/HP/Desktop/Projects Fox/Task 10 - SQL/app/swagger/api/student_course.yaml'
tags:
  - name: Students
    description: Operations related to students
  - name: Groups
    description: Operations related to groups
  - name: Courses
    description: Operations related to courses
  - name: StudentCourse
    description: Operations related to student-course associations
